// DemoLocalization.cpp
// Copyright (C) 2010 Audiokinetic Inc 
/// \file 
/// Defines the methods declared in DemoLocalization.h.

#include "stdafx.h"
#include "Platform.h"

#include <AK/SoundEngine/Common/AkSoundEngine.h>    // Sound engine

#include "../WwiseProject/GeneratedSoundBanks/Wwise_IDs.h"		// IDs generated by Wwise
#include "Menu.h"
#include "IntegrationDemo.h"
#include "DemoLocalization.h"
#include <iostream>

/////////////////////////////////////////////////////////////////////
// DemoLocalization Public Methods
/////////////////////////////////////////////////////////////////////

DemoLocalization::DemoLocalization( Menu& in_ParentMenu ):Page( in_ParentMenu, "Localization Demo" )
{
	m_szHelp  = "This page shows how to implement localization by "
				"unloading and reloading language-specific SoundBanks.\n\n"
				"Use the \"Language\" control to toggle between the "
				"available languages, then press the \"Say Hello\" "
				"item to hear a greeting in the selected language.";
}

bool DemoLocalization::Init()
{
	// Load the sound bank
	AkBankID bankID; // Not used
	// if ( AK::SoundEngine::LoadBank( "Human.bnk", AK_DEFAULT_POOL_ID, bankID ) != AK_Success )
	/*if ( AK::SoundEngine::LoadBank( "SNB_PlasmaGun_IM.bnk", AK_DEFAULT_POOL_ID, bankID ) != AK_Success )
	{
		SetErrorMessage( "Human.bnk" );
		return false;
	}*/
	AK::SoundEngine::LoadBank("SNB_Ambience.bnk", AK_DEFAULT_POOL_ID, bankID);
	/*AK::SoundEngine::LoadBank("SNB_Autocannon_CM.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_Autocannon_IM.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_AutocannonHand_CM.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_BigShoota_ORK.bnk", AK_DEFAULT_POOL_ID, bankID);*/
	AK::SoundEngine::LoadBank("SNB_BolterGun_CM.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_BolterGun_IM.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_BoltPistol_CM.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_BoltPistol_IM.bnk", AK_DEFAULT_POOL_ID, bankID);
	/*AK::SoundEngine::LoadBank("SNB_Boomkannon_ORK.bnk", AK_DEFAULT_POOL_ID, bankID);*/
	AK::SoundEngine::LoadBank("SNB_Building_A.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_Building_B.bnk", AK_DEFAULT_POOL_ID, bankID);
	/*AK::SoundEngine::LoadBank("SNB_CeremonialKnife_EL.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_ChainAxe_CM.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_ChainSword_CM.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_ChainSword_EL.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_ChainSword_IM.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_ChainSword_ORK.bnk", AK_DEFAULT_POOL_ID, bankID);*/
	AK::SoundEngine::LoadBank("SNB_Characters.bnk", AK_DEFAULT_POOL_ID, bankID);
	/*AK::SoundEngine::LoadBank("SNB_ChoppaAxe_ORK.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_ChoppaBlade_ORK.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_CombatKnife_CM.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_CombatKnife_IM.bnk", AK_DEFAULT_POOL_ID, bankID);*/
	AK::SoundEngine::LoadBank("SNB_Common_Astartes.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_Common_CapturePoint.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_Common_Chaos.bnk", AK_DEFAULT_POOL_ID, bankID);
	/*AK::SoundEngine::LoadBank("SNB_Common_Eldars.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_Common_Orks.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_D_Cannon_EL.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_DakkaDeffgun_ORK.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_Demolisher_CM.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_Demolisher_IM.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_Door_Metal_Big.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_FalconGravTank_EL.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_Forcefield.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_ForceField_CM.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_Forcefield_Door.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_ForceField_IM.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_ForceFieldDoor.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_ForceSword_CM.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_ForceSword_EL.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_GearedElevator_CM.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_Glider_EL.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_GravCannon_IM.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_GravGun_IM.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_GravPistol_IM.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_Grenade_CM.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_Grenade_EL.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_Grenade_ORK.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_Grenades.bnk", AK_DEFAULT_POOL_ID, bankID);*/
	AK::SoundEngine::LoadBank("SNB_Grunts_CM.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_Grunts_IM.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_HeavyBolter_CM.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_HeavyBolter_IM.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_Hormagaunt.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_ImprovisedShield_ORK.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_JumpPack_CM.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_JumpPack_IM.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_KannonDeffgun_ORK.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_Large_Gate.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_LargeGate_CM.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_Lasblaster_EL.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_LasCannon_CM.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_LasCannon_IM.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_LootedAutocannon_ORK.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_MeltaGun_CM.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_MeltaGun_EL.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_MeltaGun_IM.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_MeltaMulti_CM.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_MeltaMulti_EL.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_MeltaMulti_IM.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_MeltaPistol_EL.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_Music.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_Narthecium_CM.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_Narthecium_IM.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_PlasmaCannon_CM.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_PlasmaCannon_IM.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_PlasmaDeffgun_ORK.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_PlasmaGun_CM.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_PlasmaGun_IM.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_PlasmaPistol_CM.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_PlasmaPistol_IM.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_PokkitRokkitLauncha_ORK.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_PowerAxe_CM.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_PowerAxe_IM.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_PowerAxe_ORK.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_PowerFist_CM.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_PowerFist_IM.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_PowerGenerator_CM.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_PowerKlaw_ORK.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_PowerSword_CM.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_PowerSword_EL.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_PowerSword_IM.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_Predator.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_Predator_CM.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_Predator_IM.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_Predator_ORK.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_Promethium.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_Proxy_SFX_CM.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_Proxy_SFX_EL.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_Proxy_SFX_IM.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_Proxy_SFX_ORK.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_Proxy_SFX_TYR.bnk", AK_DEFAULT_POOL_ID, bankID);
	/*AK::SoundEngine::LoadBank("SNB_Psychic_CM.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_Psychic_EL.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_PulseLaser_EL.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_ReaperLauncher_EL.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_RokkitLauncha_ORK.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_RokkitPack_ORK.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_ScatterLaser_EL.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_ScythingTalons_TYR.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_Shoota_ORK.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_ShurikenCannon_EL.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_ShurikenCannonTwin_EL.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_ShurikenCatapult_EL.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_ShurikenPistol_EL.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_ShurikenTwinLinked_EL.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_Slugga_ORK.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_SmallGate.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_SpikeKnuckles_ORK.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_StormBolter_CM.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_StormBolter_IM.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_StormShield_IM.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_Trukk_ORK.bnk", AK_DEFAULT_POOL_ID, bankID);*/
	AK::SoundEngine::LoadBank("SNB_UI_Gameplay.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_UI_Menu.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_UrtySyringe_ORK.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_Vehicles.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_Void_Shield.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_VoidShieldGenerator_CM.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_Weapons_Autocannon.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_Weapons_Melee.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_Weapons_Ranged.bnk", AK_DEFAULT_POOL_ID, bankID);
	AK::SoundEngine::LoadBank("SNB_ZzapDeffgun_ORK.bnk", AK_DEFAULT_POOL_ID, bankID);

	// Register the "Human" game object
	AK::SoundEngine::RegisterGameObj( GAME_OBJECT_HUMAN, "Human" );
	
	// Initlialize the page
	return Page::Init();
}

void DemoLocalization::Release()
{
	// Reset the language to English(US), in case it was changed
	AK::StreamMgr::SetCurrentLanguage( AKTEXT( "English(US)" ) );

	// Unregister the "Human" game object
	AK::SoundEngine::UnregisterGameObj( GAME_OBJECT_HUMAN );

	// Unload the sound bank
	// AK::SoundEngine::UnloadBank( "Human.bnk", NULL );
	AK::SoundEngine::UnloadBank("1086492828.bnk", NULL);
	AK::SoundEngine::UnloadBank("1355168291.bnk", NULL);
	AK::SoundEngine::UnloadBank("1433423144.bnk", NULL);
	AK::SoundEngine::UnloadBank("1551306167.bnk", NULL);
	AK::SoundEngine::UnloadBank("1796293291.bnk", NULL);
	AK::SoundEngine::UnloadBank("3157003241.bnk", NULL);
	AK::SoundEngine::UnloadBank("3805630700.bnk", NULL);
	AK::SoundEngine::UnloadBank("3991942870.bnk", NULL);
	AK::SoundEngine::UnloadBank("Character_Bank.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_Ambience.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_Autocannon_CM.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_Autocannon_IM.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_AutocannonHand_CM.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_BigShoota_ORK.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_BolterGun_CM.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_BolterGun_IM.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_BoltPistol_CM.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_BoltPistol_IM.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_Boomkannon_ORK.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_Building_A.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_Building_B.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_CeremonialKnife_EL.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_ChainAxe_CM.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_ChainSword_CM.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_ChainSword_EL.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_ChainSword_IM.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_ChainSword_ORK.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_Characters.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_ChoppaAxe_ORK.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_ChoppaBlade_ORK.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_CombatKnife_CM.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_CombatKnife_IM.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_Common_Astartes.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_Common_CapturePoint.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_Common_Chaos.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_Common_Eldars.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_Common_Orks.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_D_Cannon_EL.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_DakkaDeffgun_ORK.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_Demolisher_CM.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_Demolisher_IM.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_Door_Metal_Big.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_FalconGravTank_EL.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_FleshBorer_TYR.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_Forcefield.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_ForceField_CM.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_Forcefield_Door.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_ForceField_IM.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_ForceFieldDoor.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_ForceSword_CM.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_ForceSword_EL.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_GearedElevator_CM.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_Glider_EL.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_GravCannon_IM.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_GravGun_IM.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_GravPistol_IM.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_Grenade_CM.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_Grenade_EL.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_Grenade_ORK.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_Grenades.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_Grunts_CM.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_Grunts_IM.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_HeavyBolter_CM.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_HeavyBolter_IM.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_Hormagaunt.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_ImprovisedShield_ORK.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_JumpPack_CM.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_JumpPack_IM.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_KannonDeffgun_ORK.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_Large_Gate.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_LargeGate_CM.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_Lasblaster_EL.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_LasCannon_CM.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_LasCannon_IM.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_LootedAutocannon_ORK.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_MeltaGun_CM.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_MeltaGun_EL.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_MeltaGun_IM.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_MeltaMulti_CM.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_MeltaMulti_EL.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_MeltaMulti_IM.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_MeltaPistol_EL.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_Music.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_Narthecium_CM.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_Narthecium_IM.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_PlasmaCannon_CM.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_PlasmaCannon_IM.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_PlasmaDeffgun_ORK.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_PlasmaGun_CM.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_PlasmaGun_IM.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_PlasmaPistol_CM.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_PlasmaPistol_IM.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_PokkitRokkitLauncha_ORK.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_PowerAxe_CM.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_PowerAxe_IM.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_PowerAxe_ORK.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_PowerFist_CM.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_PowerFist_IM.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_PowerGenerator_CM.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_PowerKlaw_ORK.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_PowerSword_CM.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_PowerSword_EL.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_PowerSword_IM.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_Predator.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_Predator_CM.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_Predator_IM.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_Predator_ORK.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_Promethium.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_Proxy_SFX_CM.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_Proxy_SFX_EL.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_Proxy_SFX_IM.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_Proxy_SFX_ORK.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_Proxy_SFX_TYR.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_Psychic_CM.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_Psychic_EL.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_PulseLaser_EL.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_PvE.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_PvE_Decor.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_PvE_DrillSpire.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_PvE_DynamicFan.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_PvE_NidEgg.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_PvE_NidNest.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_QuadGun.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_QuadGun_CM.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_QuadGun_EL.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_QuadGun_IM.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_QuadGun_ORK.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_ReaperLauncher_EL.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_RokkitLauncha_ORK.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_RokkitPack_ORK.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_ScatterLaser_EL.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_ScythingTalons_TYR.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_Shoota_ORK.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_ShurikenCannon_EL.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_ShurikenCannonTwin_EL.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_ShurikenCatapult_EL.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_ShurikenPistol_EL.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_ShurikenTwinLinked_EL.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_Slugga_ORK.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_SmallGate.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_SpikeKnuckles_ORK.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_StormBolter_CM.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_StormBolter_IM.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_StormShield_IM.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_Trukk_ORK.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_TurretQuadGun_CM.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_TurretQuadGun_EL.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_TurretQuadGun_IM.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_TurretQuadGun_ORK.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_UI_Gameplay.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_UI_Menu.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_UrtySyringe_ORK.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_Vehicles.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_Void_Shield.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_VoidShieldGenerator_CM.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_Weapons_Autocannon.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_Weapons_Melee.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_Weapons_Ranged.bnk", NULL);
	AK::SoundEngine::UnloadBank("SNB_ZzapDeffgun_ORK.bnk", NULL);

	AK::SoundEngine::ClearPreparedEvents();
	// Release the page
	Page::Release();
}


/////////////////////////////////////////////////////////////////////
// DemoLocalization Private Methods
/////////////////////////////////////////////////////////////////////

void DemoLocalization::InitControls()
{
	ButtonControl* newBtn;
	ToggleControl* newToggle;

	// Add the "Say Hello" button
	newBtn = new ButtonControl( *this );
	newBtn->SetLabel( "Say \"Hello\"" );
	newBtn->SetDelegate( (PageMFP)&DemoLocalization::HelloButton_Pressed );
	m_Controls.push_back( newBtn );

	// Add the "Language" toggle
	newToggle = new ToggleControl( *this );
	newToggle->SetLabel( "Language:" );
	newToggle->AddOption( "English(US)" );
	newToggle->AddOption( "French(Canada)" );
	newToggle->SetDelegate( (PageMFP)&DemoLocalization::LanguageToggle_SelectionChanged );
	m_Controls.push_back( newToggle );
}

int i = 0;
void DemoLocalization::HelloButton_Pressed( void*, ControlEvent* )
{
	char message[63];
	sprintf(message, "%d", AK::SoundEngine::GetIDFromString("Play_Armor_Step"));
	OutputDebugStringA("kwa");
	OutputDebugStringA(message);
	AkUniqueID eventToPrepare[] = {
		AK::SoundEngine::GetIDFromString("Play_RT_FansRoom03")
	/*	55068865U,
		78762609U,
		85623454U,
		94274732U,
		95630072U,
		97455709U,
		98299536U,
		141690752U,
		160308977U,
		170675880U,
		197548962U,
		203323663U,
		215103125U,
		239627290U,
		264659575U,
		269553732U,
		276516379U,
		285102912U,
		365325280U,
		404466471U,
		421083872U,
		442592501U,
		523400788U,
		605410439U,
		635202542U,
		671272267U,
		763309221U,
		772214525U,
		789204567U,
		792712076U,
		794927722U,
		805241836U,
		913930016U,
		922035894U,
		996616797U,
		1044242602U,
		1091543213U,
		1136273311U,
		1203985193U,
		1204652234U,
		1206470129U,
		1223497614U,
		1233433466U,
		1248879508U,
		1282381504U,
		1282381507U,
		1374956395U,
		1401944394U,
		1413858777U,
		1427404291U,
		1436586138U,
		1498330783U,
		1500695173U,
		1503619925U,
		1523658196U,
		1525953924U,
		1525953927U,
		1528577903U,
		1529808428U,
		1586023648U,
		1619930596U,
		1665889603U,
		1672912446U,
		1676060661U,
		1679169854U,
		1693700393U,
		1729710513U,
		1765430189U,
		1784995699U,
		1807961209U,
		1820628088U,
		1841145685U,
		1842839783U,
		1881760332U,
		1919404297U,
		1943369440U,
		1972196605U,
		1975952408U,
		1977644338U,
		1990707041U,
		2003677738U,
		2006534042U,
		2044845253U,
		2046169516U,
		2059962223U,
		2059964532U,
		2059964535U,
		2078291829U,
		2085909760U,
		2118774920U,
		2120872363U,
		2124508778U,
		2151717176U,
		2162597904U,
		2200822045U,
		2215798738U,
		2217377658U,
		2229774096U,
		2230953564U,
		2296555770U,
		2333759337U,
		2342465475U,
		2345181830U,
		2382880135U,
		2386435496U,
		2386822726U,
		2392960172U,
		2396488848U,
		2432542613U,
		2436753030U,
		2462466683U,
		2517913596U,
		2554144701U,
		2554144703U,
		2609397507U,
		2618673757U,
		2621364473U,
		2699663926U,
		2764105556U,
		2795939514U,
		2807840186U,
		2825738797U,
		2864940760U,
		2866378676U,
		2866828609U,
		2951932624U,
		2965252903U,
		2983625421U,
		2987097209U,
		2998599753U,
		3012443991U,
		3015324718U,
		3084597396U,
		3098481549U,
		3159695841U,
		3159742573U,
		3193887991U,
		3198938380U,
		3204809033U,
		3226910629U,
		3253525377U,
		3272653473U,
		3291523984U,
		3346567036U,
		3354163231U,
		3420734927U,
		3447347300U,
		3499749422U,
		3509187527U,
		3573359014U,
		3649608739U,
		3662594737U,
		3703829241U,
		3709853272U,
		3754697394U,
		3758271387U,
		3758766247U,
		3767282099U,
		3798703130U,
		3818467938U,
		3916024447U,
		3921282236U,
		3921529600U,
		3942457656U,
		3944167965U,
		3989731860U,
		4040358953U,
		4041184886U,
		4125717337U,
		4138367285U,
		4147649748U,
		4150802035U,
		4168168895U,
		4204916793U,
		4215867960U,
		4242700933U,
		4245973085U,
		4290320529U */};

	if (i > (0/*176*/)) {
		i = 0;
	}

	AK::SoundEngine::StopAll (GAME_OBJECT_HUMAN);

	AKRESULT eResult = AK::SoundEngine::PrepareEvent(
		AK::SoundEngine::Preparation_Load,       // Preparation type: load.
		&eventToPrepare[i],        // Array of event IDs.
		1                      // Number of event IDs in the array.
	);
	// No implementation problems - AK_NotImplemented
	// Successes - AK_Success <----
	// Failures - AK_Fail  <----
	// No partial successes - AK_PartialSuccess
	// No incompatibilities - AK_NotCompatible
	// No stream problems - AK_AlreadyConnected
	// No format problems - AK_InvalidFile
	// No header size problems - AK_AudioFileHeaderTooLarge
	// No maximum reached - AK_MaxReached
	// No bad Ids - AK_InvalidID
	// Some Ids are not found - AK_IDNotFound
	/*if (eResult == AK_IDNotFound)

	{

		// Failed preparing event.
		throw i;
		// Handle error...
		
	}*/

	AK::SoundEngine::PostEvent(eventToPrepare[i], GAME_OBJECT_HUMAN);

	i = i + 1;
}

void DemoLocalization::LanguageToggle_SelectionChanged( void* in_pSender, ControlEvent* )
{
	ToggleControl* sender = (ToggleControl*)in_pSender;
	string szLang = sender->SelectedText();

	// Set global language. Through the Low-Level I/O's file location resolver, 
	// the sound bank file will be opened in <BasePath>/<Language>/.

	AkOSChar* pOsCharStr;
	CONVERT_CHAR_TO_OSCHAR(szLang.c_str() , pOsCharStr);

	if ( AK::StreamMgr::SetCurrentLanguage( pOsCharStr ) != AK_Success )
	{
		SetErrorMessage( "Error: Invalid language." );
	}

	// Reload the sound bank
	AK::SoundEngine::UnloadBank( "Human.bnk", NULL );
	AkBankID bankID; // Not used
	if ( AK::SoundEngine::LoadBank( "Human.bnk", AK_DEFAULT_POOL_ID, bankID ) != AK_Success )
	{
		SetLoadFileErrorMessage("Human.bnk" );
	}
}
